name: 'Test'
on: ['push', 'pull_request']

jobs:
  test:
    name: 'Vim ${{ matrix.vim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        neovim: [true, false]
        version: [stable, nightly]
    runs-on: '${{ matrix.os }}'
    timeout-minutes: 5
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'checkout vim-themis'
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: 'Setup Vim'
        id: 'vim'
        uses: 'rhysd/action-setup-vim@v1'
        with:
          version: '${{ matrix.version }}'
          neovim: '${{ matrix.neovim }}'
      - name: 'Run tests'
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis
